# Generated by Django 4.2.7 on 2023-11-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_mlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlist',
            name='mdesc',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
